sudo: false
os:
  - linux
  - osx

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack  

before_install:
  - | # Install stack.
    if test ! -f "$HOME/.local/bin/stack"
    then
      URL="https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64"
      curl --location "$URL" > stack.tar.gz
      gunzip stack.tar.gz
      tar -x -f stack.tar --strip-components 1
      mkdir -p "$HOME/.local/bin"
      mv stack "$HOME/.local/bin/"
    fi
    
script:
  - stack setup
  - stack --no-terminal build --pedantic
  - stack sdist

before_deploy:
  - | # Build bundle 
    export LOCAL_INSTALL_ROOT=$(stack path --local-install-root)
    # Remove "v" from tag name
    export VERSION=${TRAVIS_TAG#?}
   
    if [ "$TRAVIS_OS_NAME" == "osx" ]
    then
      export OS_NAME=macos
    else
      export OS_NAME=linux64
    fi
    
    pushd $(stack path --project-root)
    mkdir -p bundle/build/juicy-gcode-${VERSION}
    cp "$LOCAL_INSTALL_ROOT/bin/juicy-gcode" bundle/build/juicy-gcode-${VERSION}
    cp README.md bundle/build/juicy-gcode-${VERSION}
    cp LICENSE bundle/build/juicy-gcode-${VERSION}
    pushd bundle/build
    tar -zcvf ../juicy-gcode-${VERSION}-${OS_NAME}.tar.gz juicy-gcode-${VERSION}
    popd
    # FCIV -md5 -sha1 bundle/juicy-gcode-${VERSION}-${OS_NAME}.tar.gz > bundle/juicy-gcode-${VERSION}-${OS_NAME}.sha
    shasum bundle/juicy-gcode-${VERSION}-${OS_NAME}.tar.gz > bundle/juicy-gcode-${VERSION}-${OS_NAME}.sha
    rm -rf bundle/build
    popd

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - bundle/juicy-gcode-${VERSION}-${OS_NAME}.tar.gz
    - bundle/juicy-gcode-${VERSION}-${OS_NAME}.sha
  skip_cleanup: true
  on:
    tags: true
