sudo: false
os:
  - linux
  - osx

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack  

before_install:
  - | # Install stack.
    if test ! -f "$HOME/.local/bin/stack"
    then
      URL="https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64"
      curl --location "$URL" > stack.tar.gz
      gunzip stack.tar.gz
      tar -x -f stack.tar --strip-components 1
      mkdir -p "$HOME/.local/bin"
      mv stack "$HOME/.local/bin/"
    fi
script:
  - stack setup
  - stack --no-terminal build --pedantic
  - stack sdist
before_deploy:
  - export LOCAL_INSTALL_ROOT=$(stack path --local-install-root)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]
    then
      export OS_NAME=macos
    else
      export OS_NAME=linux64
    fi
    
  - pushd $(stack path --project-root)
  - mkdir -p bundle/build/juicy-gcode
  - cp "$LOCAL_INSTALL_ROOT/bin/juicy-gcode" bundle/build/juicy-gcode
  - cp README.md bundle/build/juicy-gcode
  - cp LICENSE bundle/build/juicy-gcode
  - pushd bundle/build
  - tar -zcvf ../${OS_NAME}.tar.gz juicy-gcode
  - popd
  - bundle/${OS_NAME}.tar.gz > bundle/${OS_NAME}.sha
  - popd
