version: '{build}'
platform: x64
cache:
  - c:\s
environment:
  STACK_ROOT: c:\s

install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -sS -o stack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
  - 7z x stack.zip stack.exe
build_script:
  - stack.exe setup
  - stack.exe --no-terminal build --only-dependencies
test_script:
  - stack.exe --no-terminal build --pedantic
  - stack.exe sdist
