version: '{build}'
platform: x64
cache:
  - c:\s
environment:
  STACK_ROOT: c:\s

install:
  - ps: curl -OutFile stack.zip -Uri https://github.com/commercialhaskell/stack/releases/download/v1.6.1/stack-1.6.1-windows-x86_64.zip
  - 7z x stack.zip stack.exe
build_script:
  - stack.exe setup
  - stack.exe --no-terminal build --only-dependencies
test_script:
  - stack.exe --no-terminal build --pedantic
  - stack.exe sdist
